### ISSUE TITLE
Where are the files downloaded in Termux

### ISSUE THREAD

**Issue by Best2Gamer** [castdrian/audiosnatch#5]
So I sucessfully installer Audiosnatch in Termux and I wanted to download an audiobook, can I change the Directory of the targeted folder?
Thank you in advance.

PS: Keep the good job up!!! This is one of the few downloader that work!!!

**Comment by Best2Gamer** [comment]
I don't have a rooted phone

**Comment by Best2Gamer** [comment]
And sorry for Bad english

**Comment by castdrian** [comment]
in the directory the application is in
